// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NailsFlow.Api.Data;

#nullable disable

namespace NailsFlow.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327125749_AddPromotionsTable")]
    partial class AddPromotionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NailsFlow.Api.Models.Appointment", b =>
                {
                    b.Property<int>("AppointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appoint_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointId"));

                    b.Property<DateTime>("AppointDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("appoint_datetime");

                    b.Property<string>("AppointStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("appoint_status");

                    b.Property<int>("PerId")
                        .HasColumnType("int")
                        .HasColumnName("cus_id");

                    b.Property<int>("SerId")
                        .HasColumnType("int")
                        .HasColumnName("ser_id");

                    b.Property<int>("UsrId")
                        .HasColumnType("int")
                        .HasColumnName("usr_id");

                    b.HasKey("AppointId");

                    b.HasIndex("PerId");

                    b.HasIndex("SerId");

                    b.HasIndex("UsrId");

                    b.ToTable("appointment");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.person", b =>
                {
                    b.Property<int>("PerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cus_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerId"));

                    b.Property<string>("CusFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cus_firstname");

                    b.Property<string>("CusLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cus_lastname");

                    b.Property<string>("CusPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cus_phone");

                    b.HasKey("PerId");

                    b.ToTable("person");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Payment", b =>
                {
                    b.Property<int>("PayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pay_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayId"));

                    b.Property<int>("AppointId")
                        .HasColumnType("int")
                        .HasColumnName("appoint_id");

                    b.Property<decimal>("PayAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pay_amount");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("pay_date");

                    b.HasKey("PayId");

                    b.HasIndex("AppointId");

                    b.ToTable("payment");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Promotion", b =>
                {
                    b.Property<int>("PromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RequiredVisits")
                        .HasColumnType("int");

                    b.Property<int>("TargetServiceId")
                        .HasColumnType("int");

                    b.HasKey("PromoId");

                    b.HasIndex("TargetServiceId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolDescripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rol_descripcion");

                    b.Property<string>("RolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rol_name");

                    b.HasKey("RolId");

                    b.ToTable("rol");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            RolDescripcion = "Acceso total al sistema",
                            RolName = "Administrador"
                        },
                        new
                        {
                            RolId = 2,
                            RolDescripcion = "Gestión de citas y servicios",
                            RolName = "Manicurista"
                        });
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Service", b =>
                {
                    b.Property<int>("SerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ser_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerId"));

                    b.Property<int>("SerDuration")
                        .HasColumnType("int")
                        .HasColumnName("ser_duration");

                    b.Property<string>("SerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ser_name");

                    b.Property<decimal>("SerPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ser_price");

                    b.HasKey("SerId");

                    b.ToTable("service");

                    b.HasData(
                        new
                        {
                            SerId = 1,
                            SerDuration = 90,
                            SerName = "Tradicional",
                            SerPrice = 15000m
                        },
                        new
                        {
                            SerId = 2,
                            SerDuration = 90,
                            SerName = "Semipermanente",
                            SerPrice = 25000m
                        },
                        new
                        {
                            SerId = 3,
                            SerDuration = 150,
                            SerName = "Dipping (Depower)",
                            SerPrice = 35000m
                        },
                        new
                        {
                            SerId = 4,
                            SerDuration = 150,
                            SerName = "Press On",
                            SerPrice = 50000m
                        },
                        new
                        {
                            SerId = 5,
                            SerDuration = 180,
                            SerName = "Polygel",
                            SerPrice = 65000m
                        });
                });

            modelBuilder.Entity("NailsFlow.Api.Models.User", b =>
                {
                    b.Property<int>("UsrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usr_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsrId"));

                    b.Property<string>("UsrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_name");

                    b.Property<string>("UsrPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_pass");

                    b.Property<string>("UsrPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_phone");

                    b.HasKey("UsrId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.UserRole", b =>
                {
                    b.Property<int>("UrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ur_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrId"));

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsrId")
                        .HasColumnType("int")
                        .HasColumnName("usr_id");

                    b.HasKey("UrId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsrId");

                    b.ToTable("user_role");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Appointment", b =>
                {
                    b.HasOne("NailsFlow.Api.Models.person", "person")
                        .WithMany()
                        .HasForeignKey("PerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NailsFlow.Api.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("SerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NailsFlow.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Payment", b =>
                {
                    b.HasOne("NailsFlow.Api.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Promotion", b =>
                {
                    b.HasOne("NailsFlow.Api.Models.Service", "TargetService")
                        .WithMany()
                        .HasForeignKey("TargetServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetService");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.UserRole", b =>
                {
                    b.HasOne("NailsFlow.Api.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NailsFlow.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
