// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NailsFlow.Api.Data;

#nullable disable

namespace NailsFlow.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406183750_refactorcodee")]
    partial class refactorcodee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NailsFlow.Api.Models.Appointment", b =>
                {
                    b.Property<int>("AppointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appoint_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointId"));

                    b.Property<DateTime>("AppointDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("appoint_datetime");

                    b.Property<string>("PaymentVoucherUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("appoint_voucherurl");

                    b.Property<int>("PerId")
                        .HasColumnType("int")
                        .HasColumnName("per_id");

                    b.Property<int>("SerId")
                        .HasColumnType("int")
                        .HasColumnName("ser_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("appoint_status");

                    b.Property<int>("UsrId")
                        .HasColumnType("int")
                        .HasColumnName("usr_id");

                    b.HasKey("AppointId");

                    b.HasIndex("PerId");

                    b.HasIndex("SerId");

                    b.HasIndex("UsrId");

                    b.ToTable("appointment");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Payment", b =>
                {
                    b.Property<int>("PayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pay_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayId"));

                    b.Property<int>("AppointId")
                        .HasColumnType("int")
                        .HasColumnName("appoint_id");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("is_approved");

                    b.Property<decimal>("PayAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pay_amount");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("pay_date");

                    b.HasKey("PayId");

                    b.HasIndex("AppointId");

                    b.ToTable("payment");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Person", b =>
                {
                    b.Property<int>("PerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("per_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerId"));

                    b.Property<DateTime?>("PerBirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("per_birthdate");

                    b.Property<string>("PerEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("per_email");

                    b.Property<string>("PerFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("per_firstname");

                    b.Property<string>("PerLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("per_lastname");

                    b.Property<string>("PerPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("per_phone");

                    b.HasKey("PerId");

                    b.ToTable("person");

                    b.HasData(
                        new
                        {
                            PerId = 1,
                            PerFirstName = "Admin",
                            PerLastName = "Principal",
                            PerPhone = "3001234567"
                        },
                        new
                        {
                            PerId = 2,
                            PerFirstName = "Manicurista",
                            PerLastName = "Prueba",
                            PerPhone = "3001234568"
                        },
                        new
                        {
                            PerId = 3,
                            PerFirstName = "Wisman",
                            PerLastName = "Admin",
                            PerPhone = "3001234569"
                        },
                        new
                        {
                            PerId = 4,
                            PerEmail = "maria@email.com",
                            PerFirstName = "María",
                            PerLastName = "García",
                            PerPhone = "3101234567"
                        },
                        new
                        {
                            PerId = 5,
                            PerEmail = "carolina@email.com",
                            PerFirstName = "Carolina",
                            PerLastName = "López",
                            PerPhone = "3112345678"
                        },
                        new
                        {
                            PerId = 6,
                            PerEmail = "andrea@email.com",
                            PerFirstName = "Andrea",
                            PerLastName = "Martínez",
                            PerPhone = "3123456789"
                        },
                        new
                        {
                            PerId = 7,
                            PerEmail = "valentina@email.com",
                            PerFirstName = "Valentina",
                            PerLastName = "Rodríguez",
                            PerPhone = "3134567890"
                        },
                        new
                        {
                            PerId = 8,
                            PerEmail = "isabella@email.com",
                            PerFirstName = "Isabella",
                            PerLastName = "Hernández",
                            PerPhone = "3145678901"
                        });
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Promotion", b =>
                {
                    b.Property<int>("PromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prom_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("prom_description");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int")
                        .HasColumnName("prom_percentage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prom_name");

                    b.Property<int>("RequiredVisits")
                        .HasColumnType("int")
                        .HasColumnName("prom_required_visits");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("prom_status");

                    b.Property<int>("TargetServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ser_id");

                    b.HasKey("PromoId");

                    b.HasIndex("TargetServiceId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolDescripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rol_descripcion");

                    b.Property<string>("RolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rol_name");

                    b.HasKey("RolId");

                    b.ToTable("rol");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            RolDescripcion = "Acceso total al sistema",
                            RolName = "Administrador"
                        },
                        new
                        {
                            RolId = 2,
                            RolDescripcion = "Gestión de citas y servicios",
                            RolName = "Manicurista"
                        },
                        new
                        {
                            RolId = 3,
                            RolDescripcion = "Usuario cliente del salón",
                            RolName = "Cliente"
                        });
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Service", b =>
                {
                    b.Property<int>("SerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ser_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerId"));

                    b.Property<int>("SerDuration")
                        .HasColumnType("int")
                        .HasColumnName("ser_duration");

                    b.Property<string>("SerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ser_name");

                    b.Property<decimal>("SerPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ser_price");

                    b.HasKey("SerId");

                    b.ToTable("service");

                    b.HasData(
                        new
                        {
                            SerId = 1,
                            SerDuration = 90,
                            SerName = "Tradicional",
                            SerPrice = 15000m
                        },
                        new
                        {
                            SerId = 2,
                            SerDuration = 90,
                            SerName = "Semipermanente",
                            SerPrice = 25000m
                        },
                        new
                        {
                            SerId = 3,
                            SerDuration = 150,
                            SerName = "Dipping (Depower)",
                            SerPrice = 35000m
                        },
                        new
                        {
                            SerId = 4,
                            SerDuration = 150,
                            SerName = "Press On",
                            SerPrice = 50000m
                        },
                        new
                        {
                            SerId = 5,
                            SerDuration = 180,
                            SerName = "Polygel",
                            SerPrice = 65000m
                        });
                });

            modelBuilder.Entity("NailsFlow.Api.Models.User", b =>
                {
                    b.Property<int>("UsrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usr_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsrId"));

                    b.Property<int>("PerId")
                        .HasColumnType("int")
                        .HasColumnName("per_id");

                    b.Property<string>("UsrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_name");

                    b.Property<string>("UsrPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_pass");

                    b.HasKey("UsrId");

                    b.HasIndex("PerId")
                        .IsUnique();

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            UsrId = 1,
                            PerId = 1,
                            UsrName = "admin",
                            UsrPass = "$2a$11$0bKHKirOLF5E1aoLuNRoBeB2AAQi8fQ2sgVi7zJP.sZPCMzgYG2Yy"
                        },
                        new
                        {
                            UsrId = 2,
                            PerId = 2,
                            UsrName = "manicurista",
                            UsrPass = "$2a$11$X0gLGIqX55fA.p8J6hL./uuV.ofpvhqrnu2xvtYwJyYxW44J1k8z."
                        },
                        new
                        {
                            UsrId = 3,
                            PerId = 3,
                            UsrName = "wisman",
                            UsrPass = "$2a$11$tf2EYYVueeq.2gqhfnefU.1oaQL2pWmIIQTsXF9p3jD2I3Yt2U9wS"
                        });
                });

            modelBuilder.Entity("NailsFlow.Api.Models.UserRole", b =>
                {
                    b.Property<int>("UrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ur_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrId"));

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsrId")
                        .HasColumnType("int")
                        .HasColumnName("usr_id");

                    b.HasKey("UrId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsrId");

                    b.ToTable("user_role");

                    b.HasData(
                        new
                        {
                            UrId = 1,
                            RolId = 1,
                            UsrId = 1
                        },
                        new
                        {
                            UrId = 2,
                            RolId = 2,
                            UsrId = 2
                        },
                        new
                        {
                            UrId = 3,
                            RolId = 1,
                            UsrId = 3
                        },
                        new
                        {
                            UrId = 4,
                            RolId = 2,
                            UsrId = 3
                        });
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Appointment", b =>
                {
                    b.HasOne("NailsFlow.Api.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NailsFlow.Api.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("SerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NailsFlow.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Payment", b =>
                {
                    b.HasOne("NailsFlow.Api.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Promotion", b =>
                {
                    b.HasOne("NailsFlow.Api.Models.Service", "TargetService")
                        .WithMany()
                        .HasForeignKey("TargetServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TargetService");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.User", b =>
                {
                    b.HasOne("NailsFlow.Api.Models.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("NailsFlow.Api.Models.User", "PerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.UserRole", b =>
                {
                    b.HasOne("NailsFlow.Api.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NailsFlow.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.Person", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("NailsFlow.Api.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
